# Generated by Django 5.0.2 on 2024-06-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0003_alter_studentdata_casestudies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='Github',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Linkedin',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
