# Generated by Django 5.0.2 on 2024-06-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0005_alter_studentdata_github_alter_studentdata_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='Github',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Image',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Linkedin',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Resume',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
