# Generated by Django 5.0.2 on 2024-06-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0006_alter_studentdata_github_alter_studentdata_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='Github',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Linkedin',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Resume',
            field=models.TextField(null=True),
        ),
    ]
