# Generated by Django 5.0.2 on 2024-06-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0008_alter_studentdata_github_alter_studentdata_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='Authentication',
            field=models.CharField(default='Active', max_length=25),
        ),
    ]
